### ISSUE TITLE
Tujuan Produk

### ISSUE THREAD

**Issue by wafiqahcc** [wnno28/eda#1]
Memberikan Kenangan dan menyenengkan Orang, Produk ini di buat untuk membuka peluang bisnis baru yang bisa memberikan kesan manis kepada pembeli dan penggunanya.

**Comment by Kimrizyu** [comment]
Produk ini di buat untuk membuka peluang bisnis baru yang bisa memberikan kesan manis kepada pembeli dan penggunanya
