### ISSUE TITLE
Memastikan Produk sudah Sesuai

### ISSUE THREAD

**Issue by wnno28** [wnno28/eda#14]
![WhatsApp Image 2024-01-20 at 22 49 35 (1)](https://github.com/wnno28/eda/assets/155214054/7b9aaf03-7ed0-4768-970d-b9ad6a96da32)
![WhatsApp Image 2024-01-20 at 22 49 35](https://github.com/wnno28/eda/assets/155214054/82734005-4c49-49f0-a25f-11ea0b8f50cd)
![WhatsApp Image 2024-01-20 at 22 49 34](https://github.com/wnno28/eda/assets/155214054/08452646-b954-4484-8ff4-01162d2426b6)

**Comment by 200409062200016050** [comment]
![WhatsApp Image 2024-01-20 at 22 49 35 (1)](https://github.com/wnno28/eda/assets/155214054/7b9aaf03-7ed0-4768-970d-b9ad6a96da32)
![WhatsApp Image 2024-01-20 at 22 49 35](https://github.com/wnno28/eda/assets/155214054/82734005-4c49-49f0-a25f-11ea0b8f50cd)
![WhatsApp Image 2024-01-20 at 22 49 34](https://github.com/wnno28/eda/assets/155214054/08452646-b954-4484-8ff4-01162d2426b6)
