### ISSUE TITLE
Memastikan Produk Tidak Cacat

### ISSUE THREAD

**Issue by wnno28** [wnno28/eda#15]
https://github.com/wnno28/eda/assets/155214054/20271a8d-31c4-4a9c-8808-fe350872b554

![WhatsApp Image 2024-01-20 at 14 25 48_a6626e9d](https://github.com/wnno28/eda/assets/155214054/eaa71aa5-221e-4c39-b52e-454ef4130108)

**Comment by 200409062200016050** [comment]
https://github.com/wnno28/eda/assets/155214054/90c15927-941c-48d0-b821-df28cbe899f9

**Comment by 200409062200016050** [comment]
https://github.com/wnno28/eda/assets/155214054/20271a8d-31c4-4a9c-8808-fe350872b554
