### ISSUE TITLE
analisis hasil pengujian produk

### ISSUE THREAD

**Issue by Kimrizyu** [wnno28/eda#20]
**ANALISIS HASIL PENGUJIAN PRODUK**

Produk Sweet Box adalah sebuah produk yang berisikan  makanan ringan atau snack seperti coklat, permen, dan kue kering. Sweet Box sering sekali di gunakan untuk hampers atau hadiah ke berbagai acara seperti, ulang tahun, hari special, wisuda, pernikahan. 
Tujuan dari analisis hasil pengujian produk ini adalah untuk mengetahui kualitas produk kepada pengguna, apakah produk ini layak atau tidak untuk di perjual belikan.
Metode yang digunakan dalam pengujian produk ini menggunakan metode kuesioner dan wawancara. Metode Kuesioner untuk disebarkan kepada pengguna atau calon konsumen dari berbagai kalangan, sedangkan wawancara dilakukan dengan pengembang produk dan penjual.
Hasil dari pengujian produk adalah kualitas yang baik dan konsumen puas dengan snack atau makanan yang disajikan didalam box. Namun ada beberapa hal yang mungkin harus di perhatikan dan di perbarui mengenai kuliats produk yaitu dengan desain kemasan, keragaman isi box mungkin bisa diganti dengan beberapa barang lainnya atau mungkin bisa ditambah dengan isi snack lainnya dan kemudian untuk harga, konsumen menginginkan harga yang terjangkau
Kesimpulan nya adalah produk sweet box ini bisa dapat berkembang dengan potensi yang tinggi, dengan melakukan perbaikan dan menambahkan beberapa aspek, produk ini dapat menjadi pilihan lebih menarik pengguna.

**Comment by 200409062200016050** [comment]
**ANALISIS HASIL PENGUJIAN PRODUK**

Produk Sweet Box adalah sebuah produk yang berisikan  makanan ringan atau snack seperti coklat, permen, dan kue kering. Sweet Box sering sekali di gunakan untuk hampers atau hadiah ke berbagai acara seperti, ulang tahun, hari special, wisuda, pernikahan. 
Tujuan dari analisis hasil pengujian produk ini adalah untuk mengetahui kualitas produk kepada pengguna, apakah produk ini layak atau tidak untuk di perjual belikan.
Metode yang digunakan dalam pengujian produk ini menggunakan metode kuesioner dan wawancara. Metode Kuesioner untuk disebarkan kepada pengguna atau calon konsumen dari berbagai kalangan, sedangkan wawancara dilakukan dengan pengembang produk dan penjual.
Hasil dari pengujian produk adalah kualitas yang baik dan konsumen puas dengan snack atau makanan yang disajikan didalam box. Namun ada beberapa hal yang mungkin harus di perhatikan dan di perbarui mengenai kuliats produk yaitu dengan desain kemasan, keragaman isi box mungkin bisa diganti dengan beberapa barang lainnya atau mungkin bisa ditambah dengan isi snack lainnya dan kemudian untuk harga, konsumen menginginkan harga yang terjangkau
Kesimpulan nya adalah produk sweet box ini bisa dapat berkembang dengan potensi yang tinggi, dengan melakukan perbaikan dan menambahkan beberapa aspek, produk ini dapat menjadi pilihan lebih menarik pengguna.
