### ISSUE TITLE
Target Pemasaran

### ISSUE THREAD

**Issue by wnno28** [wnno28/eda#4]
Target yang akan di tuju adalah orang-orang yang mencari hadiah untuk berbagai kesempatan seperti ulang tahun, pernikahan, perayaan, atau liburan Fokus pada usia, minat, dan preferensi untuk menciptakan sweet box yang sesuai dengan selera target konsumen.

https://github.com/wnno28/eda/assets/155221421/904bb6e6-7887-4949-916e-f44d05e74380

**Comment by Kimrizyu** [comment]
Hadiah dan Kenang-kenangan:

- Target yang akan di tuju adalah orang-orang yang mencari hadiah untuk berbagai kesempatan seperti ulang tahun, pernikahan, perayaan, atau liburan.
- Fokus pada segmentasi usia, minat, dan preferensi untuk menciptakan sweet box yang sesuai dengan selera target konsumen.
